import React from "react";
import ScheduleTable from "./ScheduleTable";
import Footer from "../Footer";

function Schedules_Jan() {
  const events = [
    {
      league: "Killer Motorsports Racing",
      date: "1/10/24",
      time: "8:30 PM",
      class: "UMP Mods, Super Late Models",
      track: "Lernerville",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "1/10/24",
      time: "9:30 PM",
      class: "Big Blocks, Street Stocks",
      track: "Grant Park",
    },
    {
      league: "SCRA",
      date: "1/10/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "I-55",
    },
    {
      league: "FCL",
      date: "1/11/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Lincoln",
    },
    {
      league: "Runnin Wild",
      date: "1/11/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Diamond Grove",
    },
    {
      league: "Night Owl League",
      date: "1/12/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Knoxville",
    },
    {
      league: "Runnin Wild",
      date: "1/12/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Jacobs County",
    },
    {
      league: "Wild Joker Racing",
      date: "1/12/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Baxterville",
    },
    {
      league: "FCL",
      date: "1/12/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Volusia",
    },
    {
      league: "Federated Raceway",
      date: "1/12/24",
      time: "10:15 PM",
      class: "Super Late Models, UMP Mods, Pro Late Models",
      track: "I-55",
    },
    {
      league: "NOL- ",
      date: "1/12/24",
      time: "10:30 PM",
      class: "UMP Mods",
      track: "Eldora",
    },
    {
      league: "Night Owl League",
      date: "1/13/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Kokomo",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/13/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Weedport",
    },
    {
      league: "Night Owl League",
      date: "1/13/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Kokomo",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "1/13/24",
      time: "9:30 PM",
      class: "Super Late Models, Midgets",
      track: "Knoxville, Norris County",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/14/24",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Prairie Creek",
    },
    {
      league: "Fast Action Racing Series",
      date: "1/14/24",
      time: "7:30 PM",
      class: "Street Stocks",
      track: "Kenyon County",
    },
    {
      league: "Two Three Racing Series",
      date: "1/14/24",
      time: "8:00 PM",
      class: "Super Late Models",
      track: "Straight River",
    },
    {
      league: "Runnin Wild",
      date: "1/14/24",
      time: "8:15 PM",
      class: "Big Blocks",
      track: "Praire View",
    },
    {
      league: "FCL",
      date: "1/14/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Kenyon County",
    },
    {
      league: "Fast Action Racing Series",
      date: "1/14/24",
      time: "9:00 PM",
      class: "410 sprints, Pro Late Models",
      track: "Knoxville Speedway",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "1/14/24",
      time: "9:30 PM",
      class: "Midgets, Super Late Models, UMP Mods",
      track: "Durango Park, Fairbury",
    },
    {
      league: "Cloud Nine",
      date: "1/15/24",
      time: "10:00 PM",
      class: "Big Blocks, Pro Lates",
      track: "I-55",
    },
    {
      league: "Rip the Lip",
      date: "1/15/24",
      time: "10:15 PM",
      class: "Street Stocks",
      track: "Fairbury, Norris County",
    },
    {
      league: "VOR Street Stocks",
      date: "1/16/24",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Port Royal",
    },
    {
      league: "Grit and Glory",
      date: "1/16/24",
      time: "8:30 PM",
      class: "Super Late Models, UMP Mods, Street Stocks",
      track: "Jacobs County",
    },
    {
      league: "NYDRL",
      date: "1/16/24",
      time: "9:00 PM",
      class: "Midgets, 360 Sprints",
      track: "Diamond Grove, Limaland",
    },
    {
      league: "SCRA",
      date: "1/16/24",
      time: "8:15 PM",
      class: "Pro Late Models",
      track: "Eldora",
    },

    {
      league: "Rip the Lip",
      date: "1/17/24",
      time: "10:15 PM",
      class: "Super Late Models",
      track: "Fairbury, Norris County",
    },
    {
      league: "SCRA",
      date: "1/17/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "Baxterville",
    },
    {
      league: "FCL",
      date: "1/18/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Texas",
    },
    {
      league: "Runnin Wild",
      date: "1/18/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Cedar Lake",
    },
    {
      league: "Night Owl League",
      date: "1/19/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "I-55",
    },
    {
      league: "Runnin Wild",
      date: "1/19/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "I-19",
    },
    {
      league: "FCL",
      date: "1/19/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Lernerville",
    },
    {
      league: "Federated Raceway",
      date: "1/19/24",
      time: "10:15 PM",
      class: "Super Late Models, UMP Mods, Pro Late Models",
      track: "I-55",
    },
    {
      league: "NOL- ",
      date: "1/19/24",
      time: "10:30 PM",
      class: "UMP Mods",
      track: "Old MIll",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/20/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Five Forks",
    },
    {
      league: "Night Owl League",
      date: "1/20/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Lernerville",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/21/24",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Roper Mountain",
    },
    {
      league: "Fast Action Racing Series",
      date: "1/21/24",
      time: "7:30 PM",
      class: "Street Stocks",
      track: "Arrowwood",
    },
    {
      league: "Two Three Racing Series",
      date: "1/21/24",
      time: "8:00 PM",
      class: "Super Late Models",
      track: "Limaland",
    },
    {
      league: "Runnin Wild",
      date: "1/21/24",
      time: "8:15 PM",
      class: "Big Blocks",
      track: "Old MIll",
    },
    {
      league: "FCL",
      date: "1/21/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Sugarbush",
    },
    {
      league: "Fast Action Racing Series",
      date: "1/21/24",
      time: "9:00 PM",
      class: "410 sprints, Pro Late Models",
      track: "Eldora Speedway",
    },
    {
      league: "NYDRL",
      date: "1/22/24",
      time: "9:00 PM",
      class: "Big Blocks, UMP Mods",
      track: "Lincoln, Lernverville",
    },
    {
      league: "Cloud Nine",
      date: "1/22/24",
      time: "10:00 PM",
      class: "Big Blocks, Pro Lates",
      track: "Port Royal",
    },
    {
      league: "Rip the Lip",
      date: "1/22/24",
      time: "10:15 PM",
      class: "Street Stocks",
      track: "I-55, Kenyon",
    },
    {
      league: "VOR Street Stocks",
      date: "1/23/24",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Texas",
    },
    {
      league: "Grit and Glory",
      date: "1/23/24",
      time: "8:30 PM",
      class: "Super Late Models, UMP Mods, Street Stocks",
      track: "Kenyon County",
    },
    {
      league: "NYDRL",
      date: "1/23/24",
      time: "9:00 PM",
      class: "Midgets, 360 Sprints",
      track: "Elm Creek, Cedar Lake",
    },
    {
      league: "SCRA",
      date: "1/23/24",
      time: "8:15 PM",
      class: "Pro Late Models",
      track: "Grant Park",
    },
    {
      league: "Killer Motorsports Racing",
      date: "1/24/24",
      time: "8:30 PM",
      class: "UMP Mods, Super Late Models",
      track: "Lincoln",
    },
    {
      league: "Rip the Lip",
      date: "1/24/24",
      time: "10:15 PM",
      class: "Super Late Models",
      track: "Charlotte, Volusia",
    },
    {
      league: "SCRA",
      date: "1/24/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "I-19",
    },
    {
      league: "FCL",
      date: "1/25/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Port Royal",
    },
    {
      league: "Runnin Wild",
      date: "1/25/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Bristol",
    },
    {
      league: "Night Owl League",
      date: "1/26/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Jacobs County",
    },
    {
      league: "Runnin Wild",
      date: "1/26/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Durango",
    },
    {
      league: "FCL",
      date: "1/26/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Madison Lake",
    },
    {
      league: "Federated Raceway",
      date: "1/26/24",
      time: "10:15 PM",
      class: "Super Late Models, UMP Mods, Pro Late Models",
      track: "I-55",
    },
    {
      league: "NOL- ",
      date: "1/26/24",
      time: "10:30 PM",
      class: "UMP Mods",
      track: "Jacobs County",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/27/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Grant Park",
    },
    {
      league: "Night Owl League",
      date: "1/27/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Texas",
    },
    {
      league: "Stoned N Baked Racing",
      date: "1/28/24",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "I-19",
    },
  ];

  return (
    <>
      <ScheduleTable events={events} />
      <Footer />
    </>
  );
}

export default Schedules_Jan;
