import React from "react";
import ScheduleTable from "./ScheduleTable";
import Footer from "../Footer";

function Schedules_Dec() {
  const events = [
    {
      league: "Night Owl League",
      date: "12/1/23",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Limaland",
    },
    {
      league: "Runnin Wild",
      date: "12/1/23",
      time: "8:15 EST",
      class: "Pro Late Models",
      track: "Limaland",
    },
    {
      league: "2023 Pro Late Models Tour",
      date: "12/2/23",
      time: "8:30 PM",
      class: "Pro Late Models",
      track: "I-55",
    },
    {
      league: "2023 Pro Late Models Tour",
      date: "12/2/23",
      time: "8:30 PM",
      class: "Pro Late Models",
      track: "Cedar Lake",
    },
    {
      league: "Night Owl League",
      date: "12/2/23",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Grant Park",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/2/23",
      time: "9:30 PM",
      class: "Midgets, Super Late Models",
      track: "I-55",
    },
    {
      league: "NADSL -North American Dirt Sliders",
      date: "12/3/23",
      time: "6:00 PM",
      class: "UMP Modifieds",
      track: "Cedar Lake",
    },
    {
      league: "Stoned N Baked Racing",
      date: "12/3/23",
      time: "7:00 PM",
      class: "UMP Mods Pro Late Models",
      track: "Desert Rock",
    },
    {
      league: "Fast Action Series",
      date: "12/3/23",
      time: "9:00 PM",
      class: "Random",
      track: "Lucas Oil",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/3/23",
      time: "9:30 PM",
      class: "Pro Late Models, UMP Modifieds",
      track: "Limaland",
    },
    {
      league: "Dirty Money Racing",
      date: "12/3/23",
      time: "8 PM EST",
      class: "Super Late Models",
      track: "Jacobs County",
    },
    {
      league: "Runnin Wild",
      date: "12/3/23",
      time: "8:15 EST",
      class: "Big Blocks",
      track: "Limaland",
    },
    {
      league: "5M Extreme Racing Series",
      date: "12/3/23",
      time: "TBD",
      class: "Street Stocks, Pro Late Models",
      track: "Cedar Lake",
    },
    {
      league: "SCRA - LuAu At Limaland",
      date: "12/4/23",
      time: "8:15 PM",
      class: "5 Classes",
      track: "Limaland",
    },
    {
      league: "Cloud Nine Racing",
      date: "12/4/23",
      time: "9:30 PM",
      class: "Big Blocks, Pro Late Models",
      track: "Fairbury",
    },
    {
      league: "ESR",
      date: "12/5/23",
      time: "7:30 PM",
      class: "UMP Mods, Big Blocks, Super Lates",
      track: "Desert Rock",
    },
    {
      league: "VOR Street Stocks",
      date: "12/5/23",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Knoxville",
    },
    {
      league: "SCRA - LuAu At Limaland",
      date: "12/5/23",
      time: "8:15 PM",
      class: "Ump Modifieds",
      track: "Limaland",
    },
    {
      league: "Cloud Nine Racing",
      date: "12/5/23",
      time: "9:30 PM",
      class: "Ump Modifieds, Midgets",
      track: "Lernerville",
    },
    {
      league: "SCRA - LuAu At Limaland",
      date: "12/6/23",
      time: "8:15 PM",
      class: "Ump Modifieds",
      track: "Limaland",
    },
    {
      league: "Top Gun Dirt series",
      date: "12/6/23",
      time: "9:10 PM",
      class: "Super Late Models, 410 Sprints",
      track: "Jacobs County",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/6/23",
      time: "9:30 PM",
      class: "Street Stocks, Big Blocks",
      track: "Lincoln, Five Forks",
    },
    {
      league: "Runnin Wild",
      date: "12/7/23",
      time: "8:15 EST",
      class: "UMP Modifieds",
      track: "I-19",
    },
    {
      league: "Night Owl League",
      date: "12/8/23",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Fairbury",
    },
    {
      league: "Runnin Wild",
      date: "12/8/23",
      time: "8:15 EST",
      class: "Pro Late Models",
      track: "Fairbury",
    },
    {
      league: "2023 Pro Late Models Tour",
      date: "12/9/23",
      time: "8:30 PM",
      class: "Pro Late Models",
      track: "Lincoln",
    },
    {
      league: "Night Owl League",
      date: "12/9/23",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Millstone",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/9/23",
      time: "9:30 PM",
      class: "Midgets, Super Late Models",
      track: "I-19, Durango Park",
    },
    {
      league: "NADSL -North American Dirt Sliders",
      date: "12/10/23",
      time: "6:00 PM",
      class: "Pro Late Models",
      track: "Lincoln",
    },
    {
      league: "Stoned N Baked Racing",
      date: "12/10/23",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Kenyon County",
    },
    {
      league: "Fast Action Series",
      date: "12/10/23",
      time: "9:00 PM",
      class: "Random",
      track: "Knoxville",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/10/23",
      time: "9:30 PM",
      class: "Midgets, Super Late Models",
      track: "I-84",
    },
    {
      league: "Dirty Money Racing",
      date: "12/10/23",
      time: "8 PM EST",
      class: "Pro Late Models",
      track: "I-55",
    },
    {
      league: "5M Extreme Racing Series",
      date: "12/10/23",
      time: "TBD",
      class: "Street Stocks, Pro Late Models",
      track: "I-19",
    },
    {
      league: "Cloud Nine Racing",
      date: "12/11/23",
      time: "9:30 PM",
      class: "Big Blocks, Pro Late Models",
      track: "Texas",
    },
    {
      league: "Rip the Lip",
      date: "12/11/23",
      time: "10:15 PM",
      class: "Street Stocks",
      track: "Grant Park, Sterling County",
    },
    {
      league: "ESR",
      date: "12/12/23",
      time: "7:30 PM",
      class: "UMP Mods, Big Blocks, Super Lates",
      track: "Eldora",
    },
    {
      league: "VOR Street Stocks",
      date: "12/12/23",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Kokomo",
    },
    {
      league: "Cloud Nine Racing",
      date: "12/12/23",
      time: "9:30 PM",
      class: "Ump Modifieds, Midgets",
      track: "Charlotte",
    },
    {
      league: "Top Gun Dirt series",
      date: "12/13/23",
      time: "9:10 PM",
      class: "Super Late Models, 410 Sprints",
      track: "Millstone",
    },
    {
      league: "Rip the Lip",
      date: "12/13/23",
      time: "10:15 PM",
      class: "Super Late Models",
      track: "Texas, Sterling County",
    },
    {
      league: "Runnin Wild",
      date: "12/14/23",
      time: "8:15 EST",
      class: "UMP Modifieds",
      track: "Volusia",
    },
    {
      league: "Night Owl League",
      date: "12/15/23",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Kokomo",
    },
    {
      league: "Runnin Wild",
      date: "12/15/23",
      time: "8:15 EST",
      class: "Pro Late Models",
      track: "Texas",
    },
    {
      league: "2023 Pro Late Models Tour",
      date: "12/16/23",
      time: "8:30 PM",
      class: "Pro Late Models",
      track: "Texas",
    },
    {
      league: "Night Owl League",
      date: "12/16/23",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Sheep Mountain",
    },
    {
      league: "NADSL -North American Dirt Sliders",
      date: "12/17/23",
      time: "6:00 PM",
      class: "Midgets",
      track: "Baxterville",
    },
    {
      league: "Stoned N Baked Racing",
      date: "12/17/23",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Old Mill",
    },
    {
      league: "Fast Action Series",
      date: "12/17/23",
      time: "9:00 PM",
      class: "Random",
      track: "Eldora",
    },
    {
      league: "5M Extreme Racing Series",
      date: "12/17/23",
      time: "TBD",
      class: "Street Stocks, Pro Late Models",
      track: "Charlotte",
    },
    {
      league: "Cloud Nine Racing",
      date: "12/18/23",
      time: "9:30 PM",
      class: "Big Blocks, Pro Late Models",
      track: "Lucas Oil",
    },
    {
      league: "Rip the Lip",
      date: "12/18/23",
      time: "10:15 PM",
      class: "Street Stocks",
      track: "Dimaond Grove, Limaland",
    },
    {
      league: "VOR Street Stocks",
      date: "12/19/23",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Las Vegas",
    },
    {
      league: "Top Gun Dirt series",
      date: "12/20/23",
      time: "9:10 PM",
      class: "Super Late Models, 410 Sprints",
      track: "Baxterville",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/20/23",
      time: "9:30 PM",
      class: "Street Stocks, Big Blocks",
      track: "Sawtooth, Lernverville",
    },
    {
      league: "Rip the Lip",
      date: "12/20/23",
      time: "10:15 PM",
      class: "Super Late Models",
      track: "Sheep Mountain, Limaland",
    },
    {
      league: "Night Owl League",
      date: "12/22/23",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Five Forks",
    },
    {
      league: "Night Owl League",
      date: "12/23/23",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "SugarBush",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/23/23",
      time: "9:30 PM",
      class: "Midgets, Super Late Models",
      track: "Chili Bowl, Baxterville",
    },
    {
      league: "NADSL -North American Dirt Sliders",
      date: "12/24/23",
      time: "6:00 PM",
      class: "Super Late Models",
      track: "Charlotte",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/26/23",
      time: "9:30 PM",
      class: "Pro Late Models, UMP Modifieds",
      track: "Jacobs County",
    },
    {
      league: "Top Gun Dirt series",
      date: "12/27/23",
      time: "9:10 PM",
      class: "Super Late Models, 410 Sprints",
      track: "Volusia",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/27/23",
      time: "9:30 PM",
      class: "Street Stocks, Big Blocks",
      track: "Fairbury",
    },
    {
      league: "Night Owl League",
      date: "12/29/23",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Kenyon County",
    },
    {
      league: "Night Owl League",
      date: "12/30/23",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Cedar Lake",
    },
    {
      league: "BCRL Banging Cushions Racing League",
      date: "12/30/23",
      time: "9:30 PM",
      class: "Midgets, Super Late Models",
      track: "Sterling County, Port Royal",
    },
  ];

  return (
    <>
      <ScheduleTable events={events} />
      <Footer />
    </>
  );
}

export default Schedules_Dec;
