import React from "react";
import ScheduleTable from "./ScheduleTable";
import Footer from "../Footer";

function Schedules_Feb() {
  const events = [
    {
      league: "FCL",
      date: "2/1/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Faribury",
    },
    {
      league: "Runnin Wild",
      date: "2/1/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Lincoln",
    },
    {
      league: "Night Owl League",
      date: "2/2/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Grant Park",
    },
    {
      league: "Runnin Wild",
      date: "2/2/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Willow Creek",
    },
    {
      league: "FCL",
      date: "2/2/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Cedar Lake",
    },
    {
      league: "Federated Raceway",
      date: "2/2/24",
      time: "10:15 PM",
      class: "Super Late Models, UMP Mods, Pro Late Models",
      track: "I-55",
    },
    {
      league: "NOL- ",
      date: "2/2/24",
      time: "10:30 PM",
      class: "UMP Mods",
      track: "Texas",
    },
    {
      league: "Stoned N Baked Racing",
      date: "2/3/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Prairie Creek",
    },
    {
      league: "Night Owl League",
      date: "2/3/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Baxterville",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/4/24",
      time: "7:30 PM",
      class: "Street Stocks",
      track: "Sugarbush",
    },
    {
      league: "Two Three Racing Series",
      date: "2/4/24",
      time: "8:00 PM",
      class: "Super Late Models",
      track: "Sugarbush",
    },
    {
      league: "Runnin Wild",
      date: "2/4/24",
      time: "8:15 PM",
      class: "Big Blocks",
      track: "I-19",
    },
    {
      league: "FCL",
      date: "2/4/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Arrowwood",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/4/24",
      time: "9:00 PM",
      class: "410 sprints",
      track: "Woodley Speedway",
    },

    {
      league: "NYDRL",
      date: "2/5/24",
      time: "9:00 PM",
      class: "Big Blocks",
      track: "I-19",
    },

    {
      league: "Rip the Lip",
      date: "2/5/24",
      time: "10:15 PM",
      class: "Street Stocks",
      track: "TBA",
    },
    {
      league: "VOR Street Stocks",
      date: "2/6/24",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Straight River",
    },
    {
      league: "Grit and Glory",
      date: "2/6/24",
      time: "8:30 PM",
      class: "Super Late Models, UMP Mods, Street Stocks",
      track: "Eldora",
    },
    {
      league: "NYDRL",
      date: "2/6/24",
      time: "9:00 PM",
      class: "Midgets, 360 Sprints",
      track: "Cedar Lake, Baxterville",
    },
    {
      league: "SCRA",
      date: "2/6/24",
      time: "8:15 PM",
      class: "Pro Late Models",
      track: "Jacobs County",
    },
    {
      league: "Killer Motorsports Racing",
      date: "2/7/24",
      time: "8:30 PM",
      class: "UMP Mods, Super Late Models",
      track: "Texas, Volusia",
    },
    {
      league: "SCRA",
      date: "2/7/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "Texas",
    },
    {
      league: "FCL",
      date: "2/8/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Praire View",
    },
    {
      league: "Runnin Wild",
      date: "2/8/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Fairbury",
    },
    {
      league: "Night Owl League",
      date: "2/9/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Texas",
    },
    {
      league: "Runnin Wild",
      date: "2/9/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Lernerville",
    },
    {
      league: "FCL",
      date: "2/9/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Port Royal",
    },
    {
      league: "Federated Raceway",
      date: "2/9/24",
      time: "10:15 PM",
      class: "305 Sprints, 360 Sprints, 410 Sprints",
      track: "I-55",
    },
    {
      league: "NOL- ",
      date: "2/9/24",
      time: "10:30 PM",
      class: "UMP Mods",
      track: "Straight River",
    },
    {
      league: "Stoned N Baked Racing",
      date: "2/10/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Straight River",
    },
    {
      league: "Night Owl League",
      date: "2/10/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Five Forks",
    },
    {
      league: "Stoned N Baked Racing",
      date: "2/11/24",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Jacobs County",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/11/24",
      time: "7:30 PM",
      class: "Street Stocks",
      track: "Prairie Creek",
    },
    {
      league: "Two Three Racing Series",
      date: "2/11/24",
      time: "8:00 PM",
      class: "Super Late Models",
      track: "Durango",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/11/24",
      time: "9:00 PM",
      class: "410 sprints, Pro Late Models",
      track: "Roper Mountain",
    },
    {
      league: "NYDRL",
      date: "2/12/24",
      time: "9:00 PM",
      class: "Big Blocks, UMP Mods",
      track: "Volusia, Sugarbush",
    },
    {
      league: "VOR Street Stocks",
      date: "2/13/24",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Williams Grove",
    },
    {
      league: "NYDRL",
      date: "2/13/24",
      time: "9:00 PM",
      class: "Midgets, 360 Sprints",
      track: "I-19, Weedsport",
    },
    {
      league: "SCRA",
      date: "2/13/24",
      time: "8:15 PM",
      class: "Pro Late Models",
      track: "Limaland",
    },
    {
      league: "SCRA",
      date: "2/14/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "Cedar Lake",
    },
    {
      league: "FCL",
      date: "2/15/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Baxterville",
    },
    {
      league: "Runnin Wild",
      date: "2/15/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Straight River",
    },
    {
      league: "Night Owl League",
      date: "2/16/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "Durango Park",
    },
    {
      league: "Runnin Wild",
      date: "2/16/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Cedar Lake",
    },
    {
      league: "FCL",
      date: "2/16/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "I-55",
    },
    {
      league: "Federated Raceway",
      date: "2/16/24",
      time: "10:15 PM",
      class: "Super Late Models, UMP Mods, Pro Late Models",
      track: "I-55",
    },
    {
      league: "Stoned N Baked Racing",
      date: "2/17/24",
      time: "8:50 PM",
      class: "Super Late Models",
      track: "Lernerville",
    },
    {
      league: "Night Owl League",
      date: "2/17/24",
      time: "9:00 PM",
      class: "Super Late Models",
      track: "Jacobs County",
    },
    {
      league: "Stoned N Baked Racing",
      date: "2/18/24",
      time: "7:00 PM",
      class: "UMP Mods, Pro Late Models",
      track: "Grant Park",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/18/24",
      time: "7:30 PM",
      class: "Street Stocks",
      track: "Durango Park",
    },
    {
      league: "Two Three Racing Series",
      date: "2/18/24",
      time: "8:00 PM",
      class: "Super Late Models",
      track: "Volusia",
    },
    {
      league: "Runnin Wild",
      date: "2/18/24",
      time: "8:15 PM",
      class: "Big Blocks",
      track: "Fairbury",
    },
    {
      league: "FCL",
      date: "2/18/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "I-19",
    },
    {
      league: "Fast Action Racing Series",
      date: "2/18/24",
      time: "9:00 PM",
      class: "410 sprints, Pro Late Models",
      track: "Baxterville",
    },
    {
      league: "NYDRL",
      date: "2/19/24",
      time: "9:00 PM",
      class: "Big Blocks, UMP Mods",
      track: "Desert Rock, Five Forks",
    },
    {
      league: "VOR Street Stocks",
      date: "2/20/24",
      time: "7:45 PM",
      class: "Street Stocks",
      track: "Lernerville",
    },
    {
      league: "NYDRL",
      date: "2/20/24",
      time: "9:00 PM",
      class: "Midgets, 360 Sprints",
      track: "Madison Lake, Five Forks",
    },
    {
      league: "SCRA",
      date: "2/20/24",
      time: "8:15 PM",
      class: "Pro Late Models",
      track: "Volusia",
    },
    {
      league: "SCRA",
      date: "2/21/24",
      time: "8:15 PM",
      class: "UMP Modifieds",
      track: "Kenyon County",
    },
    {
      league: "FCL",
      date: "2/22/24",
      time: "8:00 PM",
      class: "360 Sprints",
      track: "Cedar Lake",
    },
    {
      league: "Runnin Wild",
      date: "2/22/24",
      time: "9:15 PM",
      class: "Ump Mods",
      track: "Lernerville",
    },
    {
      league: "Night Owl League",
      date: "2/23/24",
      time: "8:00 PM",
      class: "UMP Modfieds",
      track: "I-19, Limaland",
    },
    {
      league: "Runnin Wild",
      date: "2/23/24",
      time: "8:15 PM",
      class: "Super Late Models",
      track: "Straight River",
    },
    {
      league: "FCL",
      date: "2/23/24",
      time: "9:00 PM",
      class: "UMP Modifieds",
      track: "Fairbury",
    },
  ];

  return (
    <>
      <ScheduleTable events={events} />
      <Footer />
    </>
  );
}

export default Schedules_Feb;
